### ISSUE TITLE
 Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Lowlowlowlowlowlow** [Ruu3f/perplexityai#1]
Details:

(base) root@vultr:~# python demo.py 
👦: "hi"
🤖: Expecting value: line 1 column 1 (char 0)
👦: 

How to slove it?

**Comment by Ruu3f** [comment]
Oh, sorry. It likely couldn't get a successful response from perplexity.ai and returned an empty string. I will improve the error handling in the code.

**Comment by Dima-369** [comment]
I always get this error message from now. Same on https://github.com/nathanrchn/perplexityai actually.

Does anyone know of a fix?

**Comment by Ruu3f** [comment]
It is fixed now.

**Comment by Dima-369** [comment]
> It is fixed now.

Amazing, thanks. I can confirm that it works now!

**Comment by LexiestLeszek** [comment]
I have the same issue, how to fix it? And strangely, I have it when my app is deployed on Vercel/Render, but when I run it locally with Ngrok - it works perfectly.

**Comment by Dima-369** [comment]
> And strangely, I have it when my app is deployed on Vercel/Render

Is it possible that you have an old version of this repo code installed there? Because locally this also works fine for me.

**Comment by LexiestLeszek** [comment]
> > And strangely, I have it when my app is deployed on Vercel/Render
> 
> Is it possible that you have an old version of this repo code installed there? Because locally this also works fine for me.

Hey Dima. It works locally for me as well, the problem that it doesn't work when I deploy it on Vercel/Render/PythonAnywhere.

**Comment by LexiestLeszek** [comment]
bump, still having it whenever try to deploy app in the internet but with ngrok it works just fine
