### ISSUE TITLE
raise JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by LexiestLeszek** [Ruu3f/perplexityai#4]
Hello! I have an error when deploying it on Render:

  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

but when using Ngrok it works fine. How to fix it?

**Comment by LexiestLeszek** [comment]
@Ruu3f please help, I spent 3 days trying to fix it myself

**Comment by LexiestLeszek** [comment]
I think there might be something with adding "headers={"Content-Type": "application/json; charset=utf-8"}"

**Comment by Ruu3f** [comment]
It's a Cloudflare issue. Services like Render are considered as bots by Cloudflare.
