### ISSUE TITLE
Response in loop

### ISSUE THREAD

**Issue by AtulRajVAASITS** [Ruu3f/perplexityai#5]
Hi the responses are printed as loops like this:

👦: Analysis of the gig economy's effects on labor market dynamics in male
🤖: 
🤖: 
🤖:
🤖: The gig economy
🤖: The gig economy is a relatively
🤖: The gig economy is a relatively new phenomenon
🤖: The gig economy is a relatively new phenomenon that has emerged
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth in the sectors
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth in the sectors in which women
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth in the sectors in which women are most likely
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth in the sectors in which women are most likely to be concentrated
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth in the sectors in which women are most likely to be concentrated, there currently
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth in the sectors in which women are most likely to be concentrated, there currently appear to be
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth in the sectors in which women are most likely to be concentrated, there currently appear to be relatively fewer
🤖: The gig economy is a relatively new phenomenon that has emerged as a result of technological, economic, and labor market trends. While there is evidence to suggest that there will be exponential growth in the sectors in which women are most likely to be concentrated, there currently appear to be relatively fewer female than male

**Comment by Ruu3f** [comment]
That is purposefully done, you can make it only respond when it's completely done generating text by using a list.

**Comment by AtulRajVAASITS** [comment]
Okay so i will have to take the final answer from the loop when it ends right ?

**Comment by AtulRajVAASITS** [comment]
Thank you. Your project is really helpful.
